### ISSUE TITLE
Unexpected exception in the runtime when parsing an empty JSON object to a case class with Java annotations

### ISSUE THREAD

**Issue by plokhotnyuk** [reugn/scalikejackson#14]
It is unclear how fields of case classes can be marked as required, but when they have Jackson's annotations then error messages look strange:
```
scala> import reug.scalikejackson.ScalaJacksonImpl._
scala> case class Bar(@com.fasterxml.jackson.annotation.JsonProperty(required = true) foo: String)
defined class Bar

scala> implicit val barFormatter = reug.scalikejackson.play.Json.format[Bar]()
barFormatter: reug.scalikejackson.ScalaJacksonFormatter[Bar] = reug.scalikejackson.ScalaJacksonFormat@6b69d81f

scala> """{"foo":"xxx"}""".read[Bar]
res0: Bar = Bar(xxx)

scala> "{}".read[Bar]
java.lang.InternalError: Malformed class name
  at java.lang.Class.getSimpleName(Class.java:1330)
  at reug.scalikejackson.ScalaJacksonParser._serdeException(ScalaJackson.scala:68)
  at reug.scalikejackson.ScalaJacksonParser._serdeException$(ScalaJackson.scala:67)
  at reug.scalikejackson.ScalaJacksonFormat._serdeException(ScalaJackson.scala:125)
  at reug.scalikejackson.ScalaJacksonReader.read(ScalaJackson.scala:79)
  at reug.scalikejackson.ScalaJacksonReader.read$(ScalaJackson.scala:74)
  at reug.scalikejackson.ScalaJacksonFormat.read(ScalaJackson.scala:125)
  at reug.scalikejackson.ScalaJacksonImpl$StringImpl$.read$extension(ScalaJacksonImpl.scala:25)
  ... 36 elided
```

In sbt test run the error message may looks like:
```
java.lang.Exception: No Bar ScalaJacksonFormat found for json input
	at reug.scalikejackson.ScalaJacksonParser._serdeException(ScalaJackson.scala:69)
	at reug.scalikejackson.ScalaJacksonParser._serdeException$(ScalaJackson.scala:67)
	at reug.scalikejackson.ScalaJacksonFormat._serdeException(ScalaJackson.scala:125)
	at reug.scalikejackson.ScalaJacksonReader.read(ScalaJackson.scala:79)
	at reug.scalikejackson.ScalaJacksonReader.read$(ScalaJackson.scala:74)
	at reug.scalikejackson.ScalaJacksonFormat.read(ScalaJackson.scala:125)
	at reug.scalikejackson.ScalaJacksonImpl$StringImpl$.read$extension(ScalaJacksonImpl.scala:25)
```

**Comment by reugn** [comment]
@plokhotnyuk Looks like there is no implicit ClassTag for Bar from Scala REPL.

**Comment by plokhotnyuk** [comment]
> @plokhotnyuk Looks like there is no implicit ClassTag for Bar from Scala REPL.

I think that is not the case. It parses some values successfully, see lines above parsing of empty JSON object.

**Comment by reugn** [comment]
Correct. It uses ClassTag only if the reader was not found.
```scala
val cn = ctag.runtimeClass.getSimpleName
```
Otherwise works as expected.

**Comment by plokhotnyuk** [comment]
@reugn despite the issue is closed it is unclear for me how to:
1) define required fields for ScalikeJackson
2) avoid `java.lang.InternalError: Malformed class name` in Scala REPL for the case reported above
3) avoid `java.lang.Exception: No MissingRequiredFields ScalaJacksonFormat found for json input` in [the following benchmark](https://github.com/plokhotnyuk/jsoniter-scala/blob/3c50280ac1dc5cd0eeda8932fbac02d435dd1d0c/jsoniter-scala-benchmark/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/MissingRequiredFieldsReading.scala#L100-L111)

**Comment by reugn** [comment]
@plokhotnyuk  I see. Will look at "FIXME: ScalikeJackson" in benchmarks to fix things.
