### ISSUE TITLE
Binary incompatibility with jackson-module-scala 2.10.0

### ISSUE THREAD

**Issue by plokhotnyuk** [reugn/scalikejackson#19]
```
An exception or error caused a run to abort: com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.$init$(Lcom/fasterxml/jackson/module/scala/experimental/ScalaObjectMapper;)V 
java.lang.NoSuchMethodError: com.fasterxml.jackson.module.scala.experimental.ScalaObjectMapper.$init$(Lcom/fasterxml/jackson/module/scala/experimental/ScalaObjectMapper;)V
	at reug.scalikejackson.ScalaJacksonParser$$anon$1.<init>(ScalaJackson.scala:62)
	at reug.scalikejackson.ScalaJacksonParser.rawObjectMapper(ScalaJackson.scala:62)
	at reug.scalikejackson.ScalaJacksonParser.rawObjectMapper$(ScalaJackson.scala:62)
	at reug.scalikejackson.ScalaJacksonFormat.rawObjectMapper(ScalaJackson.scala:126)
	at reug.scalikejackson.ScalaJacksonParser.parseConfiguration(ScalaJackson.scala:46)
	at reug.scalikejackson.ScalaJacksonParser.parseConfiguration$(ScalaJackson.scala:45)
	at reug.scalikejackson.ScalaJacksonFormat.parseConfiguration(ScalaJackson.scala:126)
	at reug.scalikejackson.ScalaJacksonFormat.<init>(ScalaJackson.scala:127)
	at reug.scalikejackson.ScalaJacksonImpl$.<clinit>(ScalaJacksonImpl.scala:13)
```

**Comment by reugn** [comment]
@plokhotnyuk still not available on Maven Central. 2.10.0.pr3 is the latest.

**Comment by plokhotnyuk** [comment]
It is available here:
http://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.13/2.10.0/

But there is an issue with some resolvers:
https://github.com/FasterXML/jackson-databind/issues/2476
